exports.ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
exports.ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
exports.ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN';
exports.ERR_INVALID_USER = 'ERR_INVALID_USER';
exports.ERR_NOT_AN_ADMIN = 'ERR_NOT_AN_ADMIN';
exports.ERR_INVALID_FILE_TYPE = 'ERR_INVALID_FILE_TYPE';
