const ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
const ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
const ERR_INVALID_TOKEN = 'ERR_INVALID_TOKEN';

module.exports = {
  ERR_USER_NOT_FOUND,
  ERR_INVALID_PASSWORD,
  ERR_INVALID_TOKEN,
};
